//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PharmacyBatch()
        {
            this.PharmacyBatchLocations = new HashSet<PharmacyBatchLocation>();
        }
    
        public int Id { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int BatchSize { get; set; }
        public int DrugBrandId { get; set; }
    
        public virtual PharmacyDrug PharmacyDrug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyBatchLocation> PharmacyBatchLocations { get; set; }
    }
}
