//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyBatchLocation
    {
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public int BatchId { get; set; }
        public int LocationId { get; set; }
    
        public virtual PharmacyBatch PharmacyBatch { get; set; }
        public virtual PharmacyLocation PharmacyLocation { get; set; }
    }
}
