//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UzimaRxEntities : DbContext
    {
        public UzimaRxEntities()
            : base("name=UzimaRxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<PharmacyBatch> PharmacyBatches { get; set; }
        public virtual DbSet<PharmacyBatchLocation> PharmacyBatchLocations { get; set; }
        public virtual DbSet<PharmacyDrug> PharmacyDrugs { get; set; }
        public virtual DbSet<PharmacyInventory> PharmacyInventories { get; set; }
        public virtual DbSet<PharmacyLocation> PharmacyLocations { get; set; }
        public virtual DbSet<PharmacyStatu> PharmacyStatus { get; set; }
        public virtual DbSet<PharmacySupplier> PharmacySuppliers { get; set; }
    }
}
