//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UzimaInventory
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public string LastModifiedBy { get; set; }
        public System.Guid DrugId { get; set; }
        public int StatusId { get; set; }
        public System.Guid CurrentLocationId { get; set; }
        public Nullable<System.Guid> FutureLocationId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UzimaDrug UzimaDrug { get; set; }
        public virtual UzimaLocation UzimaLocation { get; set; }
        public virtual UzimaLocation UzimaLocation1 { get; set; }
        public virtual UzimaStatu UzimaStatu { get; set; }
    }
}
