//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UzimaLocationType
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string LocationType { get; set; }
        public Nullable<int> Supplier { get; set; }
    
        public virtual UzimaLocation UzimaLocation { get; set; }
        public virtual UzimaLocation UzimaLocation1 { get; set; }
    }
}
