//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UzimaRxEntities : DbContext
    {
        public UzimaRxEntities()
            : base("name=UzimaRxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UzimaDrug> UzimaDrugs { get; set; }
        public virtual DbSet<UzimaInventory> UzimaInventories { get; set; }
        public virtual DbSet<UzimaLocation> UzimaLocations { get; set; }
        public virtual DbSet<UzimaLocationType> UzimaLocationTypes { get; set; }
        public virtual DbSet<UzimaStatu> UzimaStatus { get; set; }
    }
}
