//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UzimaDrug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UzimaDrug()
        {
            this.UzimaInventories = new HashSet<UzimaInventory>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public string DrugName { get; set; }
        public string BrandName { get; set; }
        public string ApplicationNumber { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerLocation { get; set; }
        public string ApprovalNumber { get; set; }
        public string Schedule { get; set; }
        public string License { get; set; }
        public string Ingredients { get; set; }
        public string PackSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzimaInventory> UzimaInventories { get; set; }
    }
}
